import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Input from "@/ui/Input";
import Button from "@/ui/Button";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable}`}>
        <div className="border w-full h-[288px] px-6 py-8">

          <div className="flex justify-between">
            <Image src={"/Logo.svg"} width={108} height={28} alt="logo" />
            <div className="w-10 h-10 rounded-full bg-gray-200 bg-opacity-80 flex items-center justify-center overflow-hidden">
              <Image
                src={"/profile.svg"}
                width={28}
                height={28}
                alt="Profile"
                className="rounded-full object-cover"
              />
            </div>
          </div>

          <div className="flex items-center gap-4 my-8">
            <Input
              className="bg-white border border-[#C3D4E966] flex-1 max-w-sm !h-[48px] px-4"
              placeholder={"Search something here"}
            />
            <div className="w-12 h-12 border border-[#C3D4E966] rounded-[10px] flex justify-center items-center">
              <Image src={"/filter.svg"} width={24} height={24} alt="filter" />
            </div>
          </div>

          <div className="flex justify-center relative">
            <Image src={"/Ads.svg"} width={327} height={232} alt="ads" />
            <h1 className="absolute top-4 left-10 flex items-center justify-center text-white font-semibold text-base">The Best Platform for Car Rental</h1>
            <span className="absolute top-12 left-10 font-medium text-xs text-white max-w-[216px] leading-[160%]">Ease of doing a car rental safely and reliably. Of course at a low price.</span>
            <div className="absolute top-25 left-10">
              <Button size="small">Rental car</Button>
            </div>
          </div>

        </div>
        {children}
      </body>
    </html>
  );
}
